### ISSUE TITLE
The Error info means what ? thanks!!!

### ISSUE THREAD

**Issue by eleczxm** [hellovimo/uvm_testbench_gen#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/xiaoming.zhang/uvm_testbench_gen.py", line 5940, in parse_ss_button_code
    self.generic_parse_ss_and_store(self.parse_ss_sheet)
  File "/home/xiaoming.zhang/uvm_testbench_gen.py", line 6275, in generic_parse_ss_and_store
    parse_ss_max_row = len(sheet['A'])
**TypeError: list indices must be integers or slices, not str**

**Comment by eleczxm** [comment]
openpyxl             3.0.10
cfg file is：Uvm_Template_Generator_Env_Def_File.xlsx

**Comment by hellovimo** [comment]
Hello @eleczxm you got this issue when you parsed the .xlsx file ? If so did you try re parsing the .xlsx file ? Or you faced the issue again ?

**Comment by hellovimo** [comment]
Hello @eleczxm , Closing this Jira as there is no response back. Thanks.
